language: python

python:
    - 3.6

install:
    - pip3 install -e .
    - pip3 install mock pytest pytest-cov coveralls

script:
    - pip3 install '.[dev]'
    - py.test --cov=httpreplay
    - pip3 install '.[mitmproxy]'
    - py.test --cov=httpreplay --cov-append

after_success:
    - coveralls
